version: '3.8'

services:
  web:
    build:
      context: ./service
      dockerfile: Dockerfile
    container_name: jus_service
    ports:
      - "8000:8000"
    depends_on:
      - db
      - rabbitmq
    command: sh -c "alembic upgrade head && uvicorn src.main:app --host 0.0.0.0 --port 8000"

  db:
    image: postgres:13
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.9-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_VHOST: /
    volumes:
      - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
      - rabbitmq_data:/var/lib/rabbitmq
    command: >
      rabbitmq-server
      --definitions /etc/rabbitmq/definitions.json

  worker:
    build: 
      context: ./crawler
      dockerfile: Dockerfile
    container_name: jus_crawler
    depends_on:
      - db
      - rabbitmq
    command: celery -A src.main:app worker --loglevel=info --concurrency=4

volumes:
  postgres_data:
  rabbitmq_data: