"""create base tables

Revision ID: f3f6958f1446
Revises: 
Create Date: 2025-01-13 19:37:47.836223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f3f6958f1446'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('control_process',
    sa.Column('control_process_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('control_process_id'),
    sa.UniqueConstraint('control_process_id')
    )
    op.create_table('court_process',
    sa.Column('court_process_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('control_process_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('court_name', sa.String(), nullable=True),
    sa.Column('process_number', sa.String(), nullable=True),
    sa.Column('degree', sa.Integer(), nullable=True),
    sa.Column('process_class', sa.String(), nullable=True),
    sa.Column('area', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('distribution_date', sa.String(), nullable=True),
    sa.Column('judge', sa.String(), nullable=True),
    sa.Column('share_value', sa.String(), nullable=True),
    sa.Column('parts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('moves', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['control_process_id'], ['control_process.control_process_id'], ),
    sa.PrimaryKeyConstraint('court_process_id'),
    sa.UniqueConstraint('court_process_id')
    )
    op.create_index(op.f('ix_court_process_control_process_id'), 'court_process', ['control_process_id'], unique=False)
    op.create_index(op.f('ix_court_process_degree'), 'court_process', ['degree'], unique=False)
    op.create_index(op.f('ix_court_process_process_number'), 'court_process', ['process_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_court_process_process_number'), table_name='court_process')
    op.drop_index(op.f('ix_court_process_degree'), table_name='court_process')
    op.drop_index(op.f('ix_court_process_control_process_id'), table_name='court_process')
    op.drop_table('court_process')
    op.drop_table('control_process')
    # ### end Alembic commands ###
